service: aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  
functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
    events:
      - httpApi:
        method: get
        path: /hello
        
  costNotifier:
    handler: src/costNotifier.handler
    events:
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:LAMBDA_SLACK_WEBHOOK}
    iamRoleStatements:
    - Effect: Allow
      Action:
        -  ce:GetCostAndUsage
      Resource: "*"